### ISSUE TITLE
Add number of ratings to Users and Videos tabs

### ISSUE THREAD

**Issue by azhitian** [Swiddis/toasty-glicko#1]
stability is cool and all but

**Comment by Swiddis** [comment]
Stand-in solution: We can use a formula directly to avoid having to add anything to the code.

`=ARRAYFORMULA(IF(A2:A <> "", COUNTIFS('Form Responses'!C$2:C, "="&A2:A), ""))`

Tricky thing is whether to keep it like that and trust we won't need to add to the program, or just add to the program directly.

**Comment by Swiddis** [comment]
Will mark as closed for now with the formula directly in the sheet, we can revisit the issue if there's trouble scaling later on.

![Spreadsheet graphic](https://github.com/Swiddis/toasty-glicko/assets/31739405/b110f6e2-7933-41f8-960b-250ae1b6e182)
